version: "3.1"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql

    environment:

      MYSQL_DATABASE: dbtest
      MYSQL_ROOT_PASSWORD: root
  app:
    build: ./
    container_name: javaapp
    ports:
      - 8080:8080

